language: python
python:
  - "2.7"
  - "3.3"
env:
  - TEST_MONGODB=localhost
install:
  - pip install -e .
before_script:
script: nosetests  --nologcapture --nocapture --with-coverage --cover-package=lumin --cover-erase --exclude=selenium
notifications:
  irc: "irc.freenode.org#koansys"
