language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - TEST_MONGODB=localhost
install:
  - python setup.py install
before_script:
script: nosetests lumin --with-coverage --cover-erase --cover-package=lumin --cover-erase
notifications:
  irc: "irc.freenode.org#koansys"
services: mongodb
